name: Minigame
version: '1.0-SNAPSHOT'
main: com.professoreno.mc.minigame.Minigame
api-version: 1.19
commands:
  minigamespawn:
    description: spawns custom entities
    usage: /minigamespawn [customentity] [amount]